# Generated by Django 3.2.4 on 2021-07-17 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0002_auto_20210717_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('gender_other', models.CharField(blank=True, max_length=50, null=True)),
                ('marital', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Single'), (2, 'Have Friend'), (3, 'Married'), (4, 'Not Married'), (5, 'In Search Of Friend'), (6, 'Divorced'), (7, 'Widowed')])),
                ('interests', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
