# Generated by Django 3.2.4 on 2021-07-17 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0003_auto_20210717_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='UserInfo',
        ),
    ]
