# Generated by Django 3.2.4 on 2021-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_appuser_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender_other',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='marital',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
