# Generated by Django 3.2.4 on 2021-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210718_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
