# Generated by Django 3.2.4 on 2021-07-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210718_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_<django.db.models.fields.related.OneToOneField>/'),
        ),
    ]
