# Generated by Django 3.2.4 on 2021-07-19 18:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0007_userinfo_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.UserInfo.upload_to),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to=server.models.UserMedia.upload_to)),
                ('mime_type', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 7, 19, 21, 31, 0, 625055))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userinfo')),
            ],
        ),
    ]
