# Generated by Django 3.2.4 on 2021-07-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0009_auto_20210724_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='type',
            field=models.IntegerField(choices=[(0, 'Photo'), (1, 'Video')], null=True),
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined')], null=True)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendreceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendsender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
