# Generated by Django 3.2.4 on 2021-07-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20210725_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendreceiver', to='server.userinfo'),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendsender', to='server.userinfo'),
        ),
    ]
