# Generated by Django 3.2.4 on 2021-07-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210725_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendreceiver', to='server.userinfo'),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriendsender', to='server.userinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together={('sender', 'receiver')},
        ),
    ]
