# Generated by Django 3.2.4 on 2021-07-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20210725_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')], null=True),
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')])),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatreceiver', to='server.userinfo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatsender', to='server.userinfo')),
            ],
        ),
    ]
