# Generated by Django 3.2.4 on 2021-08-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20210731_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='status',
        ),
    ]
