# Generated by Django 3.2.4 on 2021-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20210801_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatuses',
            new_name='UserStatus',
        ),
    ]
